# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_caugi_wrappers", use_symbols = TRUE, package_name = "caugi")

#' @usage NULL
#' @useDynLib caugi, .registration = TRUE
NULL

edge_registry_new <- function() .Call(wrap__edge_registry_new)

edge_registry_register_builtins <- function(reg) invisible(.Call(wrap__edge_registry_register_builtins, reg))

edge_registry_seal <- function(reg) invisible(.Call(wrap__edge_registry_seal, reg))

edge_registry_len <- function(reg) .Call(wrap__edge_registry_len, reg)

edge_registry_register <- function(reg, glyph, tail_mark, head_mark, class, symmetric) .Call(wrap__edge_registry_register, reg, glyph, tail_mark, head_mark, class, symmetric)

edge_registry_code_of <- function(reg, glyphs) .Call(wrap__edge_registry_code_of, reg, glyphs)

edge_registry_spec_of_code <- function(reg, code) .Call(wrap__edge_registry_spec_of_code, reg, code)

graph_session_new <- function(reg, n, simple, class) .Call(wrap__graph_session_new, reg, n, simple, class)

graph_session_clone <- function(session) .Call(wrap__graph_session_clone, session)

graph_session_set_edges <- function(session, from, to, etype) invisible(.Call(wrap__graph_session_set_edges, session, from, to, etype))

graph_session_set_n <- function(session, n) invisible(.Call(wrap__graph_session_set_n, session, n))

graph_session_set_simple <- function(session, simple) invisible(.Call(wrap__graph_session_set_simple, session, simple))

graph_session_set_class <- function(session, class) invisible(.Call(wrap__graph_session_set_class, session, class))

graph_session_set_names <- function(session, names) invisible(.Call(wrap__graph_session_set_names, session, names))

graph_session_layout <- function(session, method) .Call(wrap__graph_session_layout, session, method)

graph_session_compute_layout <- function(session, method, packing_ratio) .Call(wrap__graph_session_compute_layout, session, method, packing_ratio)

graph_session_compute_bipartite_layout <- function(session, partition, orientation) .Call(wrap__graph_session_compute_bipartite_layout, session, partition, orientation)

graph_session_n <- function(session) .Call(wrap__graph_session_n, session)

graph_session_is_simple <- function(session) .Call(wrap__graph_session_is_simple, session)

#' Lightweight getter for the declared simple flag (no core build).
#'
#' @param session A pointer to the GraphSession Rust object.
#' @return Logical indicating if the graph is declared as simple.
#' @keywords internal
graph_session_simple <- function(session) .Call(wrap__graph_session_simple, session)

graph_session_class <- function(session) .Call(wrap__graph_session_class, session)

graph_session_graph_class <- function(session) .Call(wrap__graph_session_graph_class, session)

graph_session_names <- function(session) .Call(wrap__graph_session_names, session)

graph_session_index_of <- function(session, name) .Call(wrap__graph_session_index_of, session, name)

graph_session_indices_of <- function(session, names) .Call(wrap__graph_session_indices_of, session, names)

graph_session_edges_df <- function(session) .Call(wrap__graph_session_edges_df, session)

graph_session_is_valid <- function(session) .Call(wrap__graph_session_is_valid, session)

graph_session_topological_sort <- function(session) .Call(wrap__graph_session_topological_sort, session)

graph_session_parents_of <- function(session, idxs) .Call(wrap__graph_session_parents_of, session, idxs)

graph_session_children_of <- function(session, idxs) .Call(wrap__graph_session_children_of, session, idxs)

graph_session_undirected_of <- function(session, idxs) .Call(wrap__graph_session_undirected_of, session, idxs)

graph_session_neighbors_of <- function(session, idxs, mode) .Call(wrap__graph_session_neighbors_of, session, idxs, mode)

graph_session_ancestors_of <- function(session, node) .Call(wrap__graph_session_ancestors_of, session, node)

graph_session_descendants_of <- function(session, node) .Call(wrap__graph_session_descendants_of, session, node)

graph_session_anteriors_of <- function(session, node) .Call(wrap__graph_session_anteriors_of, session, node)

graph_session_markov_blanket_of <- function(session, node) .Call(wrap__graph_session_markov_blanket_of, session, node)

graph_session_spouses_of <- function(session, idxs) .Call(wrap__graph_session_spouses_of, session, idxs)

graph_session_exogenous_nodes <- function(session, undirected_as_parents) .Call(wrap__graph_session_exogenous_nodes, session, undirected_as_parents)

graph_session_districts <- function(session) .Call(wrap__graph_session_districts, session)

graph_session_district_of <- function(session, idx) .Call(wrap__graph_session_district_of, session, idx)

graph_session_dependency_json <- function(session) .Call(wrap__graph_session_dependency_json, session)

graph_session_is_acyclic <- function(session) .Call(wrap__graph_session_is_acyclic, session)

graph_session_is_dag_type <- function(session) .Call(wrap__graph_session_is_dag_type, session)

graph_session_is_pdag_type <- function(session) .Call(wrap__graph_session_is_pdag_type, session)

graph_session_is_ug_type <- function(session) .Call(wrap__graph_session_is_ug_type, session)

graph_session_is_admg_type <- function(session) .Call(wrap__graph_session_is_admg_type, session)

graph_session_is_ag_type <- function(session) .Call(wrap__graph_session_is_ag_type, session)

graph_session_is_mag <- function(session) .Call(wrap__graph_session_is_mag, session)

graph_session_is_cpdag <- function(session) .Call(wrap__graph_session_is_cpdag, session)

graph_session_to_cpdag <- function(session) .Call(wrap__graph_session_to_cpdag, session)

graph_session_skeleton <- function(session) .Call(wrap__graph_session_skeleton, session)

graph_session_moralize <- function(session) .Call(wrap__graph_session_moralize, session)

graph_session_latent_project <- function(session, latents) .Call(wrap__graph_session_latent_project, session, latents)

graph_session_proper_backdoor_graph <- function(session, xs, ys) .Call(wrap__graph_session_proper_backdoor_graph, session, xs, ys)

graph_session_moral_of_ancestors <- function(session, seeds) .Call(wrap__graph_session_moral_of_ancestors, session, seeds)

graph_session_ancestral_reduction <- function(session, seeds) .Call(wrap__graph_session_ancestral_reduction, session, seeds)

graph_session_induced_subgraph <- function(session, keep) .Call(wrap__graph_session_induced_subgraph, session, keep)

graph_session_d_separated <- function(session, xs, ys, z) .Call(wrap__graph_session_d_separated, session, xs, ys, z)

graph_session_m_separated <- function(session, xs, ys, z) .Call(wrap__graph_session_m_separated, session, xs, ys, z)

graph_session_adjustment_set_parents <- function(session, xs, ys) .Call(wrap__graph_session_adjustment_set_parents, session, xs, ys)

graph_session_adjustment_set_backdoor <- function(session, xs, ys) .Call(wrap__graph_session_adjustment_set_backdoor, session, xs, ys)

graph_session_adjustment_set_optimal <- function(session, xs, ys) .Call(wrap__graph_session_adjustment_set_optimal, session, xs, ys)

graph_session_is_valid_backdoor_set <- function(session, xs, ys, z) .Call(wrap__graph_session_is_valid_backdoor_set, session, xs, ys, z)

graph_session_all_backdoor_sets <- function(session, xs, ys, minimal, max_size) .Call(wrap__graph_session_all_backdoor_sets, session, xs, ys, minimal, max_size)

graph_session_is_valid_adjustment_set_admg <- function(session, xs, ys, z) .Call(wrap__graph_session_is_valid_adjustment_set_admg, session, xs, ys, z)

graph_session_all_adjustment_sets_admg <- function(session, xs, ys, minimal, max_size) .Call(wrap__graph_session_all_adjustment_sets_admg, session, xs, ys, minimal, max_size)

graph_session_shd <- function(s1, s2) .Call(wrap__graph_session_shd, s1, s2)

graph_session_hd <- function(s1, s2) .Call(wrap__graph_session_hd, s1, s2)

graph_session_ancestor_aid <- function(s_true, s_guess) .Call(wrap__graph_session_ancestor_aid, s_true, s_guess)

graph_session_oset_aid <- function(s_true, s_guess) .Call(wrap__graph_session_oset_aid, s_true, s_guess)

graph_session_parent_aid <- function(s_true, s_guess) .Call(wrap__graph_session_parent_aid, s_true, s_guess)

graph_builder_new <- function(reg, n, simple) .Call(wrap__graph_builder_new, reg, n, simple)

graph_builder_add_edges <- function(b, from, to, etype) invisible(.Call(wrap__graph_builder_add_edges, b, from, to, etype))

graph_builder_resolve_class <- function(b, class) .Call(wrap__graph_builder_resolve_class, b, class)

graph_session_compute_tiered_layout <- function(session, tier_assignments, num_tiers, orientation) .Call(wrap__graph_session_compute_tiered_layout, session, tier_assignments, num_tiers, orientation)

graph_session_write_caugi_file <- function(session, reg, graph_class, path, comment, tags) invisible(.Call(wrap__graph_session_write_caugi_file, session, reg, graph_class, path, comment, tags))

read_caugi_file <- function(path, reg) .Call(wrap__read_caugi_file, path, reg)

graph_session_serialize_caugi <- function(session, reg, graph_class, comment, tags) .Call(wrap__graph_session_serialize_caugi, session, reg, graph_class, comment, tags)

deserialize_caugi <- function(json, reg) .Call(wrap__deserialize_caugi, json, reg)

graph_session_serialize_graphml <- function(session, reg, graph_class) .Call(wrap__graph_session_serialize_graphml, session, reg, graph_class)

deserialize_graphml <- function(xml, reg) .Call(wrap__deserialize_graphml, xml, reg)


# nolint end
