# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_caugi_wrappers", use_symbols = TRUE, package_name = "caugi")

#' @usage NULL
#' @useDynLib caugi, .registration = TRUE
NULL

edge_registry_new <- function() .Call(wrap__edge_registry_new)

edge_registry_register_builtins <- function(reg) invisible(.Call(wrap__edge_registry_register_builtins, reg))

edge_registry_seal <- function(reg) invisible(.Call(wrap__edge_registry_seal, reg))

edge_registry_len <- function(reg) .Call(wrap__edge_registry_len, reg)

edge_registry_register <- function(reg, glyph, tail_mark, head_mark, class, symmetric) .Call(wrap__edge_registry_register, reg, glyph, tail_mark, head_mark, class, symmetric)

edge_registry_code_of <- function(reg, glyphs) .Call(wrap__edge_registry_code_of, reg, glyphs)

edge_registry_spec_of_code <- function(reg, code) .Call(wrap__edge_registry_spec_of_code, reg, code)

graph_session_new <- function(reg, n, simple, class) .Call(wrap__graph_session_new, reg, n, simple, class)

graph_session_clone <- function(session) .Call(wrap__graph_session_clone, session)

graph_session_set_edges <- function(session, from, to, etype) invisible(.Call(wrap__graph_session_set_edges, session, from, to, etype))

graph_session_set_n <- function(session, n) invisible(.Call(wrap__graph_session_set_n, session, n))

graph_session_set_simple <- function(session, simple) invisible(.Call(wrap__graph_session_set_simple, session, simple))

graph_session_set_class <- function(session, class) invisible(.Call(wrap__graph_session_set_class, session, class))

graph_session_set_names <- function(session, names) invisible(.Call(wrap__graph_session_set_names, session, names))

graph_session_set_cache_enabled <- function(session, enabled) invisible(.Call(wrap__graph_session_set_cache_enabled, session, enabled))

graph_session_view_ptr <- function(session) .Call(wrap__graph_session_view_ptr, session)

graph_session_layout <- function(session, method, use_checkpoint) .Call(wrap__graph_session_layout, session, method, use_checkpoint)

graph_session_clear_layout_checkpoint <- function(session) invisible(.Call(wrap__graph_session_clear_layout_checkpoint, session))

graph_session_n <- function(session) .Call(wrap__graph_session_n, session)

graph_session_class <- function(session) .Call(wrap__graph_session_class, session)

graph_session_names <- function(session) .Call(wrap__graph_session_names, session)

graph_session_is_valid <- function(session) .Call(wrap__graph_session_is_valid, session)

graph_session_topological_sort <- function(session) .Call(wrap__graph_session_topological_sort, session)

graph_session_ancestors_of <- function(session, node) .Call(wrap__graph_session_ancestors_of, session, node)

graph_session_descendants_of <- function(session, node) .Call(wrap__graph_session_descendants_of, session, node)

graph_session_anteriors_of <- function(session, node) .Call(wrap__graph_session_anteriors_of, session, node)

graph_session_markov_blanket_of <- function(session, node) .Call(wrap__graph_session_markov_blanket_of, session, node)

graph_session_exogenous_nodes <- function(session, undirected_as_parents) .Call(wrap__graph_session_exogenous_nodes, session, undirected_as_parents)

graph_session_districts <- function(session) .Call(wrap__graph_session_districts, session)

graph_session_dependency_json <- function(session) .Call(wrap__graph_session_dependency_json, session)

graph_builder_new <- function(reg, n, simple) .Call(wrap__graph_builder_new, reg, n, simple)

graph_builder_add_edges <- function(b, from, to, etype) invisible(.Call(wrap__graph_builder_add_edges, b, from, to, etype))

graph_builder_build_view <- function(b, class) .Call(wrap__graph_builder_build_view, b, class)

parents_of_ptr <- function(g, idxs) .Call(wrap__parents_of_ptr, g, idxs)

children_of_ptr <- function(g, idxs) .Call(wrap__children_of_ptr, g, idxs)

undirected_of_ptr <- function(g, idxs) .Call(wrap__undirected_of_ptr, g, idxs)

neighbors_of_ptr <- function(g, idxs, mode) .Call(wrap__neighbors_of_ptr, g, idxs, mode)

ancestors_of_ptr <- function(g, idxs) .Call(wrap__ancestors_of_ptr, g, idxs)

descendants_of_ptr <- function(g, idxs) .Call(wrap__descendants_of_ptr, g, idxs)

anteriors_of_ptr <- function(g, idxs) .Call(wrap__anteriors_of_ptr, g, idxs)

markov_blanket_of_ptr <- function(g, idxs) .Call(wrap__markov_blanket_of_ptr, g, idxs)

exogenous_nodes_of_ptr <- function(g, undirected_as_parents) .Call(wrap__exogenous_nodes_of_ptr, g, undirected_as_parents)

topological_sort_ptr <- function(g) .Call(wrap__topological_sort_ptr, g)

induced_subgraph_ptr <- function(g, keep) .Call(wrap__induced_subgraph_ptr, g, keep)

is_simple_ptr <- function(g) .Call(wrap__is_simple_ptr, g)

graph_class_ptr <- function(g) .Call(wrap__graph_class_ptr, g)

skeleton_ptr <- function(g) .Call(wrap__skeleton_ptr, g)

moralize_ptr <- function(g) .Call(wrap__moralize_ptr, g)

latent_project_ptr <- function(g, latents) .Call(wrap__latent_project_ptr, g, latents)

is_acyclic_ptr <- function(g) .Call(wrap__is_acyclic_ptr, g)

to_cpdag_ptr <- function(g) .Call(wrap__to_cpdag_ptr, g)

is_cpdag_ptr <- function(g) .Call(wrap__is_cpdag_ptr, g)

is_dag_type_ptr <- function(g) .Call(wrap__is_dag_type_ptr, g)

is_pdag_type_ptr <- function(g) .Call(wrap__is_pdag_type_ptr, g)

is_ug_type_ptr <- function(g) .Call(wrap__is_ug_type_ptr, g)

is_admg_type_ptr <- function(g) .Call(wrap__is_admg_type_ptr, g)

is_ag_type_ptr <- function(g) .Call(wrap__is_ag_type_ptr, g)

is_mag_ptr <- function(g) .Call(wrap__is_mag_ptr, g)

spouses_of_ptr <- function(g, idxs) .Call(wrap__spouses_of_ptr, g, idxs)

districts_ptr <- function(g) .Call(wrap__districts_ptr, g)

district_of_ptr <- function(g, idx) .Call(wrap__district_of_ptr, g, idx)

m_separated_ptr <- function(g, xs, ys, z) .Call(wrap__m_separated_ptr, g, xs, ys, z)

is_valid_adjustment_set_admg_ptr <- function(g, xs, ys, z) .Call(wrap__is_valid_adjustment_set_admg_ptr, g, xs, ys, z)

all_adjustment_sets_admg_ptr <- function(g, xs, ys, minimal, max_size) .Call(wrap__all_adjustment_sets_admg_ptr, g, xs, ys, minimal, max_size)

shd_of_ptrs <- function(g1, names1, g2, names2) .Call(wrap__shd_of_ptrs, g1, names1, g2, names2)

hd_of_ptrs <- function(g1, g2) .Call(wrap__hd_of_ptrs, g1, g2)

ancestor_aid_of_ptrs <- function(g_true, names_true, g_guess, names_guess) .Call(wrap__ancestor_aid_of_ptrs, g_true, names_true, g_guess, names_guess)

oset_aid_of_ptrs <- function(g_true, names_true, g_guess, names_guess) .Call(wrap__oset_aid_of_ptrs, g_true, names_true, g_guess, names_guess)

parent_aid_of_ptrs <- function(g_true, names_true, g_guess, names_guess) .Call(wrap__parent_aid_of_ptrs, g_true, names_true, g_guess, names_guess)

d_separated_ptr <- function(g, xs, ys, z) .Call(wrap__d_separated_ptr, g, xs, ys, z)

adjustment_set_parents_ptr <- function(g, xs, ys) .Call(wrap__adjustment_set_parents_ptr, g, xs, ys)

adjustment_set_backdoor_ptr <- function(g, xs, ys) .Call(wrap__adjustment_set_backdoor_ptr, g, xs, ys)

adjustment_set_optimal_ptr <- function(g, x, y) .Call(wrap__adjustment_set_optimal_ptr, g, x, y)

is_valid_backdoor_set_ptr <- function(g, x, y, z) .Call(wrap__is_valid_backdoor_set_ptr, g, x, y, z)

all_backdoor_sets_ptr <- function(g, x, y, minimal, max_size) .Call(wrap__all_backdoor_sets_ptr, g, x, y, minimal, max_size)

proper_backdoor_graph_ptr <- function(g, xs, ys) .Call(wrap__proper_backdoor_graph_ptr, g, xs, ys)

moral_of_ancestors_ptr <- function(g, seeds) .Call(wrap__moral_of_ancestors_ptr, g, seeds)

ancestral_reduction_ptr <- function(g, seeds) .Call(wrap__ancestral_reduction_ptr, g, seeds)

n_ptr <- function(g) .Call(wrap__n_ptr, g)

edges_ptr_df <- function(g) .Call(wrap__edges_ptr_df, g)

compute_layout_ptr <- function(g, method, packing_ratio) .Call(wrap__compute_layout_ptr, g, method, packing_ratio)

compute_bipartite_layout_ptr <- function(g, partition, orientation) .Call(wrap__compute_bipartite_layout_ptr, g, partition, orientation)

write_caugi_file_ptr <- function(g, reg, graph_class, node_names, path, comment, tags) invisible(.Call(wrap__write_caugi_file_ptr, g, reg, graph_class, node_names, path, comment, tags))

read_caugi_file_ptr <- function(path, reg) .Call(wrap__read_caugi_file_ptr, path, reg)

serialize_caugi_ptr <- function(g, reg, graph_class, node_names, comment, tags) .Call(wrap__serialize_caugi_ptr, g, reg, graph_class, node_names, comment, tags)

deserialize_caugi_ptr <- function(json, reg) .Call(wrap__deserialize_caugi_ptr, json, reg)

serialize_graphml_ptr <- function(g, reg, graph_class, node_names) .Call(wrap__serialize_graphml_ptr, g, reg, graph_class, node_names)

deserialize_graphml_ptr <- function(xml, reg) .Call(wrap__deserialize_graphml_ptr, xml, reg)


# nolint end
